### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by dtr0yan** [cloudcreativity/json-api#34]
It will be much better to add badges (code coverage, code climate, dependencies) to this repo.
I think it will help to promote it and shows people stability of this lib.
I am also sure laravel-json-api should have such badges

**Comment by morrme** [comment]
I agree. It adds a great polish to the README. You can include the license badge right away, and as you add  other integrations this can be added on. 


I can help if needed. 😃

**Comment by lindyhopchris** [comment]
If you were able to help that would be great. Just submit a PR to the `develop` branch.

It would really help as I'm working my way through a tonne of other changes and time is limited because of my current work projects.

**Comment by lindyhopchris** [comment]
Closing this issue as we've deprecated this package.
